/*
 * Generated by JasperReports - 21/09/17 11:25
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class list_report_1506003936394_905601 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_teste = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_respath = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillField field_parent = null;
    private JRFillField field_multicurrency_code = null;
    private JRFillField field_capital = null;
    private JRFillField field_code_client = null;
    private JRFillField field_siren = null;
    private JRFillField field_supplier_account = null;
    private JRFillField field_tva_assuj = null;
    private JRFillField field_fk_stcomm = null;
    private JRFillField field_fournisseur = null;
    private JRFillField field_customer_bad = null;
    private JRFillField field_fk_user_creat = null;
    private JRFillField field_siret = null;
    private JRFillField field_fk_departement = null;
    private JRFillField field_prefix_comm = null;
    private JRFillField field_cond_reglement = null;
    private JRFillField field_rowid = null;
    private JRFillField field_complemento = null;
    private JRFillField field_default_lang = null;
    private JRFillField field_ape = null;
    private JRFillField field_customer_rate = null;
    private JRFillField field_logo = null;
    private JRFillField field_tms = null;
    private JRFillField field_fk_typent = null;
    private JRFillField field_fax = null;
    private JRFillField field_barcode = null;
    private JRFillField field_tva_intra = null;
    private JRFillField field_zip = null;
    private JRFillField field_note_private = null;
    private JRFillField field_canvas = null;
    private JRFillField field_town = null;
    private JRFillField field_bairro = null;
    private JRFillField field_fk_user_modif = null;
    private JRFillField field_fk_incoterms = null;
    private JRFillField field_location_incoterms = null;
    private JRFillField field_remise_client = null;
    private JRFillField field_idprof6 = null;
    private JRFillField field_idprof4 = null;
    private JRFillField field_idprof5 = null;
    private JRFillField field_phone = null;
    private JRFillField field_supplier_rate = null;
    private JRFillField field_code_fournisseur = null;
    private JRFillField field_localtax2_assuj = null;
    private JRFillField field_fk_barcode_type = null;
    private JRFillField field_fk_effectif = null;
    private JRFillField field_statut = null;
    private JRFillField field_status = null;
    private JRFillField field_name_alias = null;
    private JRFillField field_code_compta = null;
    private JRFillField field_fk_pays = null;
    private JRFillField field_numero = null;
    private JRFillField field_localtax1_assuj = null;
    private JRFillField field_fk_currency = null;
    private JRFillField field_webservices_url = null;
    private JRFillField field_nom = null;
    private JRFillField field_localtax1_value = null;
    private JRFillField field_skype = null;
    private JRFillField field_mode_reglement = null;
    private JRFillField field_code_compta_fournisseur = null;
    private JRFillField field_client = null;
    private JRFillField field_datec = null;
    private JRFillField field_ref_ext = null;
    private JRFillField field_email = null;
    private JRFillField field_fk_shipping_method = null;
    private JRFillField field_outstanding_limit = null;
    private JRFillField field_cond_reglement_supplier = null;
    private JRFillField field_address = null;
    private JRFillField field_mode_reglement_supplier = null;
    private JRFillField field_fk_prospectlevel = null;
    private JRFillField field_ref_int = null;
    private JRFillField field_fk_multicurrency = null;
    private JRFillField field_url = null;
    private JRFillField field_localtax2_value = null;
    private JRFillField field_model_pdf = null;
    private JRFillField field_fk_account = null;
    private JRFillField field_import_key = null;
    private JRFillField field_note_public = null;
    private JRFillField field_price_level = null;
    private JRFillField field_fk_forme_juridique = null;
    private JRFillField field_entity = null;
    private JRFillField field_webservices_key = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_teste = (JRFillParameter)pm.get("teste");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_respath = (JRFillParameter)pm.get("respath");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_parent = (JRFillField)fm.get("parent");
        field_multicurrency_code = (JRFillField)fm.get("multicurrency_code");
        field_capital = (JRFillField)fm.get("capital");
        field_code_client = (JRFillField)fm.get("code_client");
        field_siren = (JRFillField)fm.get("siren");
        field_supplier_account = (JRFillField)fm.get("supplier_account");
        field_tva_assuj = (JRFillField)fm.get("tva_assuj");
        field_fk_stcomm = (JRFillField)fm.get("fk_stcomm");
        field_fournisseur = (JRFillField)fm.get("fournisseur");
        field_customer_bad = (JRFillField)fm.get("customer_bad");
        field_fk_user_creat = (JRFillField)fm.get("fk_user_creat");
        field_siret = (JRFillField)fm.get("siret");
        field_fk_departement = (JRFillField)fm.get("fk_departement");
        field_prefix_comm = (JRFillField)fm.get("prefix_comm");
        field_cond_reglement = (JRFillField)fm.get("cond_reglement");
        field_rowid = (JRFillField)fm.get("rowid");
        field_complemento = (JRFillField)fm.get("complemento");
        field_default_lang = (JRFillField)fm.get("default_lang");
        field_ape = (JRFillField)fm.get("ape");
        field_customer_rate = (JRFillField)fm.get("customer_rate");
        field_logo = (JRFillField)fm.get("logo");
        field_tms = (JRFillField)fm.get("tms");
        field_fk_typent = (JRFillField)fm.get("fk_typent");
        field_fax = (JRFillField)fm.get("fax");
        field_barcode = (JRFillField)fm.get("barcode");
        field_tva_intra = (JRFillField)fm.get("tva_intra");
        field_zip = (JRFillField)fm.get("zip");
        field_note_private = (JRFillField)fm.get("note_private");
        field_canvas = (JRFillField)fm.get("canvas");
        field_town = (JRFillField)fm.get("town");
        field_bairro = (JRFillField)fm.get("bairro");
        field_fk_user_modif = (JRFillField)fm.get("fk_user_modif");
        field_fk_incoterms = (JRFillField)fm.get("fk_incoterms");
        field_location_incoterms = (JRFillField)fm.get("location_incoterms");
        field_remise_client = (JRFillField)fm.get("remise_client");
        field_idprof6 = (JRFillField)fm.get("idprof6");
        field_idprof4 = (JRFillField)fm.get("idprof4");
        field_idprof5 = (JRFillField)fm.get("idprof5");
        field_phone = (JRFillField)fm.get("phone");
        field_supplier_rate = (JRFillField)fm.get("supplier_rate");
        field_code_fournisseur = (JRFillField)fm.get("code_fournisseur");
        field_localtax2_assuj = (JRFillField)fm.get("localtax2_assuj");
        field_fk_barcode_type = (JRFillField)fm.get("fk_barcode_type");
        field_fk_effectif = (JRFillField)fm.get("fk_effectif");
        field_statut = (JRFillField)fm.get("statut");
        field_status = (JRFillField)fm.get("status");
        field_name_alias = (JRFillField)fm.get("name_alias");
        field_code_compta = (JRFillField)fm.get("code_compta");
        field_fk_pays = (JRFillField)fm.get("fk_pays");
        field_numero = (JRFillField)fm.get("numero");
        field_localtax1_assuj = (JRFillField)fm.get("localtax1_assuj");
        field_fk_currency = (JRFillField)fm.get("fk_currency");
        field_webservices_url = (JRFillField)fm.get("webservices_url");
        field_nom = (JRFillField)fm.get("nom");
        field_localtax1_value = (JRFillField)fm.get("localtax1_value");
        field_skype = (JRFillField)fm.get("skype");
        field_mode_reglement = (JRFillField)fm.get("mode_reglement");
        field_code_compta_fournisseur = (JRFillField)fm.get("code_compta_fournisseur");
        field_client = (JRFillField)fm.get("client");
        field_datec = (JRFillField)fm.get("datec");
        field_ref_ext = (JRFillField)fm.get("ref_ext");
        field_email = (JRFillField)fm.get("email");
        field_fk_shipping_method = (JRFillField)fm.get("fk_shipping_method");
        field_outstanding_limit = (JRFillField)fm.get("outstanding_limit");
        field_cond_reglement_supplier = (JRFillField)fm.get("cond_reglement_supplier");
        field_address = (JRFillField)fm.get("address");
        field_mode_reglement_supplier = (JRFillField)fm.get("mode_reglement_supplier");
        field_fk_prospectlevel = (JRFillField)fm.get("fk_prospectlevel");
        field_ref_int = (JRFillField)fm.get("ref_int");
        field_fk_multicurrency = (JRFillField)fm.get("fk_multicurrency");
        field_url = (JRFillField)fm.get("url");
        field_localtax2_value = (JRFillField)fm.get("localtax2_value");
        field_model_pdf = (JRFillField)fm.get("model_pdf");
        field_fk_account = (JRFillField)fm.get("fk_account");
        field_import_key = (JRFillField)fm.get("import_key");
        field_note_public = (JRFillField)fm.get("note_public");
        field_price_level = (JRFillField)fm.get("price_level");
        field_fk_forme_juridique = (JRFillField)fm.get("fk_forme_juridique");
        field_entity = (JRFillField)fm.get("entity");
        field_webservices_key = (JRFillField)fm.get("webservices_key");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("C:\\wamp64\\www\\dolibarr\\htdocs\\reports\\societe\\images\\");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_teste.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_respath.getValue())+"simitlogo.jpg");//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.awt.Image)(it.businesslogic.ireport.barcode.BcImage.getBarcodeImage(13,"123456789010101010",false,false,null,0,0));//$JR_EXPR_ID=11$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("C:\\wamp64\\www\\dolibarr\\htdocs\\reports\\societe\\images\\");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_teste.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_respath.getValue())+"simitlogo.jpg");//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.awt.Image)(it.businesslogic.ireport.barcode.BcImage.getBarcodeImage(13,"123456789010101010",false,false,null,0,0));//$JR_EXPR_ID=11$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = (java.lang.String)("C:\\wamp64\\www\\dolibarr\\htdocs\\reports\\societe\\images\\");//$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = (java.lang.Integer)(new Integer(1));//$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = (java.lang.Integer)(new Integer(0));//$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_teste.getValue()));//$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = (java.lang.String)(((java.lang.String)parameter_respath.getValue())+"simitlogo.jpg");//$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = (java.awt.Image)(it.businesslogic.ireport.barcode.BcImage.getBarcodeImage(13,"123456789010101010",false,false,null,0,0));//$JR_EXPR_ID=11$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
